[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
backgroundColor = "#09090f"
secondaryBackgroundColor = "#16161e"
textColor = "#e8e8f0"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "viewer"
